### ISSUE TITLE
Uncaught Exception Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss

### ISSUE THREAD

**Issue by cimc0n** [itsmepetrov/homebridge-zigbee#10]
Uncaught Exception Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
    at Persistence.treatRawData (/usr/lib/node_modules/homebridge-zigbee/node_modules/nedb/lib/persistence.js:242:11)
    at /usr/lib/node_modules/homebridge-zigbee/node_modules/nedb/lib/persistence.js:281:38
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3)

**Comment by itsmepetrov** [comment]
Hi @cimc0n there is something wrong with your database file. Maybe you had added some changes manually to that file, may you don't have access in the folder where you want to store it. You can just remove the file and try again.

**Comment by cimc0n** [comment]
This problem appeared after raspberry was suddenly rebooted. Manual changes did not made. I don't even know where is this file.

**Comment by itsmepetrov** [comment]
It looks like this file wasn't properly saved and that caused the problem. If you doesn't have `database` record in your homebridge config file, you can locate db file in the same folder with the config file.

**Comment by cimc0n** [comment]
1) cd /usr/lib/node_modules/homebridge-zigbee/node_modules/nedb/lib/
2) mkdir del
3) mv persistence.js del/
4) restart service homebridge (exist with error)
5) mv persistence.js ../
6) restart service homebridge
works for me.

**Comment by itsmepetrov** [comment]
lol, ok
