### ISSUE TITLE
CC2531ZNP-2018090201.hex

### ISSUE THREAD

**Issue by Gio1978** [itsmepetrov/homebridge-zigbee#11]
I can’t download “CC2531ZNP-2018090201.hex” file

**Comment by itsmepetrov** [comment]
Network issues? )

**Comment by Gio1978** [comment]
Yes of course. It open in html

**Comment by itsmepetrov** [comment]
Hex file: https://github.com/itsmepetrov/homebridge-zigbee/blob/master/firmware/CC2531ZNP-2018090201.hex
Instruction: https://stackoverflow.com/a/13593430

![monosnap 2018-11-28 00-04-36](https://user-images.githubusercontent.com/1177226/49111465-3fde7480-f2a1-11e8-9bc5-a830e6970fc4.png)

**Comment by Gio1978** [comment]
Many thanks

**Comment by itsmepetrov** [comment]
glad to help
