### ISSUE TITLE
IKEA TRADFRI transformer 10W

### ISSUE THREAD

**Issue by loktissimo** [itsmepetrov/homebridge-zigbee#13]
Please add support for:
`[ZigBeePlatform] Unrecognized device: 0x90fd9ffffe0eb75d IKEA of Sweden TRADFRI transformer 10W
`

[IKEA Store link](https://www.ikea.com/us/en/catalog/products/10356189/)

**Comment by itsmepetrov** [comment]
@loktissimo please attach your `zigbee.db` file, you can find it in the same folder where you store `config.json` for `homebridge`

**Comment by loktissimo** [comment]
[zigbee.db.zip](https://github.com/itsmepetrov/homebridge-zigbee/files/2683457/zigbee.db.zip)
Here it is.

**Comment by itsmepetrov** [comment]
Added in https://github.com/itsmepetrov/homebridge-zigbee/commit/aee8bee2dadd37962379189632156be00faf2a24
