### ISSUE TITLE
Aqara cube

### ISSUE THREAD

**Issue by Josch90** [itsmepetrov/homebridge-zigbee#16]
I had problems adding my Aqara Cube today. This Video helped me. 
https://www.youtube.com/watch?v=uhMrcIAdGxg&feature=youtu.be
Maybee you can add it to the pairing description.
Greetings

**Comment by itsmepetrov** [comment]
It should work, there is a file which describes Aqara/Xiaomi cube: [lumi.sensor_cube.js](https://github.com/itsmepetrov/homebridge-zigbee/blob/master/lib/devices/lumi.sensor_cube.js)

**Comment by Josch90** [comment]
Yes it works perfectly after i got it to connect! Thanks for your work

**Comment by itsmepetrov** [comment]
👍
