### ISSUE TITLE
Aqara Button

### ISSUE THREAD

**Issue by mobibet** [itsmepetrov/homebridge-zigbee#2]
Кнопка Aqara WXKG11LM добавляется нормально, но не реагирует на нажатия, только при нажатии маленькой кнопочки сброс передает данные о заряде батареи. Вот так определяется `[2018-10-19 18:05:07] [ZigBee] Device announced incoming and is added, id: 0x00158d0001e893b6
[2018-10-19 18:05:09] [ZigBee] Registered device: 0x00158d0001e893b6 LUMI lumi.remote.b1acn01`

Удалил кнопку. Перезагрузил бридж, при повторном добавлении ошибка `[2018-10-19 18:42:25] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 3 of 3
[2018-10-19 18:42:25] [ZigBee] Device announced incoming and is added, id: 0x00158d0001e893b6
[2018-10-19 18:42:26] [ZigBee] Unrecognized device: 0x00158d0001e893b6 LUMI lumi.remote.b1acn01`

**Comment by fantomnotabene** [comment]
У меня такая же хрень происходит на деКонзе с Акара кубиком.

пт, 19 окт. 2018 г. в 18:23, mobibet <notifications@github.com>:

**Comment by itsmepetrov** [comment]
Please attach db file with this device

**Comment by itsmepetrov** [comment]
Fixed in https://github.com/itsmepetrov/homebridge-zigbee/commit/9bd43ec922d8abba1e5cbb83f13c6ddabb65434b
