### ISSUE TITLE
startZigBee function never returns anything

### ISSUE THREAD

**Issue by NilsBohr** [itsmepetrov/homebridge-zigbee#23]
The `homebridge-zigbee` plugin can't start.
While trying to debug the situation, I've come to the point, where it fails.
In the file index.js the following code never returns and looks like hangs indefinitelly:
```
        await zigbee.start()
```
The `zigbee.on('ready', this.handleZigBeeReady)` is never executed.

I'm not sure how to proceed with debugging, as that looks like internal `zigbee-shepherd ` code.
Would appreciate a hint.

I've tested the USB stick separately using the zigbee-shepherd alone and it works as expected, so the USB stick firmware should be OK.

Node.js is v8.15.0
NPM is v6.4.1

**Comment by itsmepetrov** [comment]
Hi @NilsBohr 

You can try to specify `port` to usb stick manually, may be port auto-detection doesn't work on your environment

**Comment by NilsBohr** [comment]
Hello @itsmepetrov 

Sorry, I forgot to mention.
I tried both to specify `port` (as "/dev/ttyACM0") and to rely on auto-detection. The result is the same.

**Comment by itsmepetrov** [comment]
Do you try it in docker? I remember I had similar problems with docker.

**Comment by itsmepetrov** [comment]
and did you flash the stick with the appropriate firmware?

**Comment by NilsBohr** [comment]
> Do you try it in docker? I remember I had similar problems with docker.
No this is regular Armbian OS on an embedded PC.

> and did you flash the stick with the appropriate firmware?
Yes, as said earlier, the stick is flashed, and I tried to launch `zigbee-shepherd` as a separate process. Works as expected.

Do you know a way to enable `zigbee-shepherd` debug messaging from within the homebridge-zigbee environment to study the issue further?

**Comment by itsmepetrov** [comment]
You need to run homebridge with DEBUG=* env variable

**Comment by itsmepetrov** [comment]
You can try to log `config` param here https://github.com/itsmepetrov/homebridge-zigbee/blob/master/lib/zigbee.js#L10

It might have the wrong port

**Comment by itsmepetrov** [comment]
And try to install the plugin from github, I've added a lot of changes so may be it will help

**Comment by NilsBohr** [comment]
> And try to install the plugin from github, I've added a lot of changes so maybe it will help

Installed from github with:
```
npm i -g git+https://github.com/itsmepetrov/homebridge-zigbee#master --unsafe-perm
```



> You can try to log `config` param here https://github.com/itsmepetrov/homebridge-zigbee/blob/master/lib/zigbee.js#L10
> 
> It might have the wrong port

Looks good to me:
```
Feb 13 15:31:44 homebridge homebridge[1854]: config { port: '/dev/ttyACM0',
Feb 13 15:31:44 homebridge homebridge[1854]:   db: '/var/lib/homebridge/zigbee.db',
Feb 13 15:31:44 homebridge homebridge[1854]:   panId: 65535,
Feb 13 15:31:44 homebridge homebridge[1854]:   channel: 11 }
```



> You need to run homebridge with DEBUG=* env variable

Perfect thnx.

I've figured out the problem.
The user `homebridge` which was launching the process was not in the `dialout` group and therefore couldn't access the Serial Port.
```
Feb 13 15:38:53 homebridge homebridge[2023]: 2019-02-13T15:38:53.431Z serialport:main opening path: /dev/ttyACM0
Feb 13 15:38:53 homebridge homebridge[2023]: 2019-02-13T15:38:53.434Z serialport:bindings open
Feb 13 15:38:53 homebridge homebridge[2023]: 2019-02-13T15:38:53.448Z serialport:main _read queueing _read for after open
Feb 13 15:38:53 homebridge homebridge[2023]: 2019-02-13T15:38:53.488Z serialport:main Binding #open had an error Error: Error: Permission denied, cannot open /dev/ttyACM0
```

Once I've added the user to the `dialout` group it worked.
Thanks for your help, the issue is closed.
