### ISSUE TITLE
Elgato Eve history service in near future?

### ISSUE THREAD

**Issue by mrdc** [itsmepetrov/homebridge-zigbee#31]
Hello,

Are there any plans to include Elgato Eve history service for ZigBee accessories? Would be nice to have it for temp&humidity sensors. 
FYI: Some source code can be found here: https://github.com/simont77/fakegato-history
and here: https://github.com/hannseman/homebridge-mi-hygrothermograph/blob/master/lib/accessory.js

**Comment by itsmepetrov** [comment]
Hi @mrdc, it has already been implemented, try to install this plugin from github:

npm i -g itsmepetrov/homebridge-zigbee

**Comment by mrdc** [comment]
Yes, I've installed it already. In Eve app I see no history (there no drop down diagram) for Aqara Temp and Humidity sensors. For Xiaomi BLE Temp and Humidity I have history.

**Xiaomi BLE:**
![photo_2019-05-07_00-48-33](https://user-images.githubusercontent.com/16876990/57257370-dccbe780-7061-11e9-877d-cf7df499ef92.jpg)

**Aqara ZigBee:**
![photo_2019-05-07_00-48-28](https://user-images.githubusercontent.com/16876990/57257377-e48b8c00-7061-11e9-912c-4c9ce7182086.jpg)

**Comment by mrdc** [comment]
I've found the problem: npm homebridge-zigbee was outdated: without fakegato libs. Updated with itsmepetrov/homebridge-zigbee and history and pressure are working now.
Thank you!
