### ISSUE TITLE
Не устанавливается

### ISSUE THREAD

**Issue by Dedcad** [itsmepetrov/homebridge-zigbee#4]
У меня не получается установить через Homebridge на уже работающую малину.
Захожу в HomeBridge, нахожу плагин, нажимаю установить в новом окне висит следующий текст:
USER: pi...........] | fetchMetadata: sill resolveWithNewModule homebridge-zigb
DIR: /usr/lib/node_modules
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-zigbee@latest

[..................] - fetchMetadata: sill resolveWithNewModule homebridge-zigb

в журнале висит такое:

[2018-10-29 10:11:55] [Config] You are using a depreciated log config format, please update your config.json to use this new format:
[2018-10-29 10:11:55] [Config] {"method":"systemd","service":"homebridge"}
      pi : TTY=pts/6 ; PWD=/home/pi/.homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
send hb to: 0x0000000002f5bc2f
{"id":-1,"method":"get_prop","params":["power","bright","rgb"]}

**Comment by itsmepetrov** [comment]
Is the issue still actual?
