### ISSUE TITLE
Device unpaired and disapeared randomly

### ISSUE THREAD

**Issue by tomaae** [itsmepetrov/homebridge-zigbee#49]
Hi,
homebridge-zigbee unpaired my device without me prompting it. I was not even using homebridge in any way at that time.
Any idea how to prevent this? Device should never just disappear on its own even if its inaccessible.

Oct 31 06:35:56 nc-nas1 homebridge[30885]: [10/31/2019, 6:35:56 AM] [ZigBee] Unpairing device: 0x00158d0003fb7337
Oct 31 06:36:06 nc-nas1 homebridge[30885]: [10/31/2019, 6:36:06 AM] [ZigBee] Unable to unpairing properly, trying to unregister device: 0x00158d0003fb7337
Oct 31 06:36:06 nc-nas1 homebridge[30885]: [10/31/2019, 6:36:06 AM] [ZigBee] Device has been unpaired: 0x00158d0003fb7337

**Comment by Olepir** [comment]
Which device was it?

**Comment by tomaae** [comment]
it was Xiaomi Wireless Switch

**Comment by Olepir** [comment]
Could it be that there was power outage or someone played with this switch turning it on/off 5 times in a row?

**Comment by tomaae** [comment]
No, there was no power outage and nobody had access to device or server. Server is on UPS, so power outage would not affect anything anyway.
