### ISSUE TITLE
Permit join delete

### ISSUE THREAD

**Issue by Hussamfhaily** [itsmepetrov/homebridge-zigbee#50]
Hi. I have tried to delete the plugin and reinstall it. How can I delete the permit join button? Thanks.

**Comment by Olepir** [comment]
Stop Homebridge process or service, delete cachedAccessories file, start Homebridge again.

**Comment by Hussamfhaily** [comment]
> Stop Homebridge process or service, delete cachedAccessories file, start Homebridge again.

Thanks for your reply. I wonder if that will effect other accessories in my homebridge.

**Comment by Olepir** [comment]
> Thanks for your reply. I wonder if that will effect other accessories in my homebridge.

No
