### ISSUE TITLE
Device removing

### ISSUE THREAD

**Issue by Maxwell70** [itsmepetrov/homebridge-zigbee#6]
@itsmepetrov Большая просьба добавить возможность удаления устройств без запуска режима спаривания на самом устройстве. Спасибо!

**Comment by itsmepetrov** [comment]
Implemented in https://github.com/itsmepetrov/homebridge-zigbee/commit/4115f221b2d7d1a189077ad6d7dcbafe1a1ae201 via custom property:

![ezgif-4-cefdda403145](https://user-images.githubusercontent.com/1177226/48097301-93255000-e22a-11e8-9b6e-ba98534c724e.gif)
