### ISSUE TITLE
Не обновляется плагин

### ISSUE THREAD

**Issue by Maxwell70** [itsmepetrov/homebridge-zigbee#7]
В вебморде при нажатии кнопки "обновить" плагин до версии 1.1.0 запускается обновление, но потом фактически показывает, что плагин не обновился.

**Comment by itsmepetrov** [comment]
Hi, which image do you use?

Please paste your ‘.npmrc’ config here, you can do it with following command:

‘’’
cat ~/.npmrc
‘’’

**Comment by Maxwell70** [comment]
@itsmepetrov 
<img width="1274" alt="2018-11-04 19 12 44" src="https://user-images.githubusercontent.com/33258356/47963955-b9e65980-e065-11e8-8a83-6b0f396d5a70.png">

**Comment by itsmepetrov** [comment]
No, you need to do it with ssh, connect to pi and run command from my previous comment and attach result here.

**Comment by itsmepetrov** [comment]
Please remove last two lines from this config and try to update again

**Comment by Maxwell70** [comment]
@itsmepetrov где и как мне удалить строки?

**Comment by itsmepetrov** [comment]
You can use any editors for that, for example `nano`:

```
nano ~/.npmrc
```

then remove lines and save file with following hotkeys:

```
Ctrl + O
```

then type 

```
Y
```

then

```
Ctrl + X
```

**Comment by Maxwell70** [comment]
@itsmepetrov помогло. Спасибо!
