### ISSUE TITLE
1/2 клавишные выключатели с нулем

### ISSUE THREAD

**Issue by pospelius** [itsmepetrov/homebridge-zigbee#8]
Привет
Не определяются выключатели с нулем

**Comment by itsmepetrov** [comment]
I need more information, please provide device info (name, model ...) and db if possible

**Comment by pospelius** [comment]
1 кл выключатель
0x00158d00028aba4c LUMI lumi.ctrl_ln1.aq1

**Comment by pospelius** [comment]
2 кл выключатель
0x00158d000244аа25 LUMI lumi.ctrl_ln2.aq1

**Comment by itsmepetrov** [comment]
Added in https://github.com/itsmepetrov/homebridge-zigbee/commit/42a57c2ed3d95fbde681f49bc4305cc59046f39f, please verify

**Comment by itsmepetrov** [comment]
Verified, it works as expected
